[build]
  base = "."
  command = "npm run build"
  publish = "dist/spa"

<<<<<<< HEAD
[build.environment]
  NODE_VERSION = "18"

=======
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
>>>>>>> e2e9c72a36e51a0b681d98fbfd99bde2493d0fb8
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
<<<<<<< HEAD

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data:; font-src 'self' https: data:; connect-src 'self' https:;"
    Permissions-Policy = "clipboard-write=*"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
=======
  to = "/.netlify/functions/api/:splat"

# Form processing configuration
[forms]
  # Enable form spam protection
  spam_protection = true
  
# Optional: Email notifications for new submissions
# [[notifications]]
#   type = "email"
#   event = "submission-created"
#   to = "your-email@domain.com"
#   subject = "New AI Toolkit Signup"
>>>>>>> e2e9c72a36e51a0b681d98fbfd99bde2493d0fb8
